# -*- coding: utf-8 -*-
"""linear regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_8weHonsu3eEmvxPVlJVjNMft2eXr1Gw
"""

#method used   #1 ordinary least squares   #2 using gradient descent algorithm


import pandas as pd     
df = pd.read_csv('/content/Salary_Data (1).csv')    
df

df.info()

x = df.iloc[:,[0]].values  
y = df.iloc[:,1].values

from sklearn.linear_model import LinearRegression       
model = LinearRegression()
model.fit(x,y)     
y_pred = model.predict(x)       
y_pred

y

model.coef_

model.intercept_

model.predict([[9.4]])

import matplotlib.pyplot as plt
plt.scatter(x,y)  
plt.plot(x,y_pred, c = 'r')

import numpy as np
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y,y_pred))
print(r2_score(y,y_pred)*100)        #model is 95.6% accurate